from lapszabasz.fit import FitAlgorithms
from lapszabasz.sorting import SortingByRectangles
from lapszabasz.step_by_step import StepByStepAlgorithms
from lapszabasz.statistics import step_by_step_selection